name: Build APK Desa Cluring

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter (Kunci ke Generasi Dart 2)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
          channel: 'stable'

      - name: Ambil Dependencies
        run: flutter pub get

      - name: Buat Kamus Bahasa (Localization)
        run: flutter gen-l10n

      - name: Buat File Auto-Generate (Build Runner)
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build APK Android
        run: flutter build apk --release

      - name: Simpan Hasil APK
        uses: actions/upload-artifact@v4
        with:
          name: Aplikasi-Desa-Cluring
          path: build/app/outputs/flutter-apk/app-release.apk
